# Generated by Django 3.0.3 on 2020-06-22 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=220)),
                ('content', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(default='', max_length=550)),
                ('timstamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
