# Generated by Django 3.0.3 on 2020-06-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20200623_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemjson', models.TextField()),
                ('name', models.CharField(default='', max_length=220)),
                ('email', models.CharField(default='', max_length=300)),
                ('phone', models.IntegerField(default=0, max_length=15)),
                ('adress', models.TextField()),
                ('thanks', models.BooleanField(default=False)),
            ],
        ),
    ]
